[global]
developmentMode = false

[server]
headless = true
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#1B365D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"

[logger]
level = "info"

[client]
showErrorDetails = false

[runner]
magicEnabled = true